apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
- ../../base
- ingress.yaml
- externalsecrets/argocd-secret.yaml
- clusters

patches:
  - target:
      kind: Service
      name: argocd-server
    patch: |
      - op: add
        path: /spec/type
        value: NodePort
      - op: add
        path: /spec/ports/0/nodePort
        value: 30100
      - op: add
        path: /spec/ports/1/nodePort
        value: 30101

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: argocd-gpg-keys-cm
    behavior: merge
    files:
      - configs/argocd-gpg-keys/362D63A80853D4CF
