apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
- ../../base
- ingresses/argocd-server-http.yaml
- ingresses/argocd-server-https.yaml
- externalsecrets/argocd-secret.yaml
- middlewares/redirect-http-https.yaml
- clusters

patches:
  - target:
      kind: Service
      name: argocd-server
    patch: |
      - op: add
        path: /spec/type
        value: NodePort
      - op: add
        path: /spec/ports/0/nodePort
        value: 30100
      - op: add
        path: /spec/ports/1/nodePort
        value: 30101

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: argocd-gpg-keys-cm
    behavior: merge
    files:
      - configs/argocd-gpg-keys/362D63A80853D4CF

  - name: argocd-notifications-cm
    behavior: merge
    files:
      - configs/argocd-notifications/service.webhook.discord
      - configs/argocd-notifications/subscriptions
      - configs/argocd-notifications/template.app-deployed
      - configs/argocd-notifications/template.app-sync-status-unknown
      - configs/argocd-notifications/template.app-sync-succeeded
      - configs/argocd-notifications/template.app-sync-running
      - configs/argocd-notifications/template.app-created
      - configs/argocd-notifications/template.app-deleted
      - configs/argocd-notifications/template.app-health-degraded
      - configs/argocd-notifications/template.app-sync-failed
      - configs/argocd-notifications/context
