apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  argocd.argoproj.io/secret-type: cluster

secretGenerator:
  - name: infra-cluster
    files:
      - infra-cluster/config
      - infra-cluster/name
      - infra-cluster/server

generatorOptions:
  disableNameSuffixHash: true
