apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
- namespace.yaml
- https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
- projects/default.yaml

configMapGenerator:
- name: argocd-cmd-params-cm
  behavior: merge
  envs:
    - configs/argocd-cmd-params.env

- name: argocd-cm
  behavior: merge
  files:
    - configs/argocd/resource.customizations.health.networking.k8s.io_Ingress
    - configs/argocd/application.instanceLabelKey

generatorOptions:
  disableNameSuffixHash: true
