apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
- namespace.yaml
- https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
- projects/default.yaml

patches:
  - path: clusterroles/argocd-server_patch.yaml
    target:
      kind: ClusterRole
      name: argocd-server

configMapGenerator:
- name: argocd-cmd-params-cm
  behavior: merge
  envs:
    - configs/argocd-cmd-params.env

- name: argocd-cm
  behavior: merge
  files:
    - configs/argocd/resource.customizations.health.networking.k8s.io_Ingress
    - configs/argocd/application.instanceLabelKey
    - configs/argocd/exec.enabled

- name: argocd-notifications-cm
  behavior: merge
  files:
    - configs/argocd-notifications/trigger.on-deployed
    - configs/argocd-notifications/trigger.on-sync-running
    - configs/argocd-notifications/template.app-deployed
    - configs/argocd-notifications/template.app-sync-status-unknown
    - configs/argocd-notifications/trigger.on-sync-status-unknown
    - configs/argocd-notifications/template.app-sync-succeeded
    - configs/argocd-notifications/trigger.on-created
    - configs/argocd-notifications/trigger.on-deleted
    - configs/argocd-notifications/trigger.on-sync-failed
    - configs/argocd-notifications/template.app-sync-running
    - configs/argocd-notifications/trigger.on-health-degraded
    - configs/argocd-notifications/trigger.on-sync-succeeded
    - configs/argocd-notifications/template.app-created
    - configs/argocd-notifications/template.app-deleted
    - configs/argocd-notifications/template.app-health-degraded
    - configs/argocd-notifications/template.app-sync-failed

generatorOptions:
  disableNameSuffixHash: true
